version: "2"

output:
  sort-order:
    - file
    - linter
    - severity

linters:
  settings:
    errcheck:
      exclude-functions:
        - fmt.Sscanf
        - io.Copy
        - (*net.TCPConn).CloseWrite
  exclusions:
    presets:
      - std-error-handling
